//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountLedger()
        {
            this.AdditionalCosts = new HashSet<AdditionalCost>();
            this.AdvancePayments = new HashSet<AdvancePayment>();
            this.LedgerPostings = new HashSet<LedgerPosting>();
            this.ContraDetails = new HashSet<ContraDetail>();
            this.ContraMasters = new HashSet<ContraMaster>();
            this.CreditNoteDetails = new HashSet<CreditNoteDetail>();
            this.DailySalaryVoucherMasters = new HashSet<DailySalaryVoucherMaster>();
            this.DebitNoteDetails = new HashSet<DebitNoteDetail>();
        }
    
        public int Id { get; set; }
        public int AccountGroupId { get; set; }
        public int PricingLevelId { get; set; }
        public int AreaId { get; set; }
        public int RouteId { get; set; }
        public string LedgerName { get; set; }
        public string OpeningBalance { get; set; }
        public bool IsDefault { get; set; }
        public string CrOrDr { get; set; }
        public string AffectGrossProfit { get; set; }
        public string MailingName { get; set; }
        public string Narration { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> CreditPeriod { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public bool BillByBill { get; set; }
        public string TIN { get; set; }
        public string CST { get; set; }
        public string PAN { get; set; }
        public string BankAccountNumber { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        public virtual Area Area { get; set; }
        public virtual PricingLevel PricingLevel { get; set; }
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalCost> AdditionalCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvancePayment> AdvancePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerPosting> LedgerPostings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraDetail> ContraDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraMaster> ContraMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditNoteDetail> CreditNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailySalaryVoucherMaster> DailySalaryVoucherMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitNoteDetail> DebitNoteDetails { get; set; }
    }
}
