//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalCost
    {
        public int Id { get; set; }
        public int VoucherTypeId { get; set; }
        public int LedgerId { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AccountLedger AccountLedger { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
