//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancePayment
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int LedgerId { get; set; }
        public int SuffixPrefixId { get; set; }
        public int VoucherTypeId { get; set; }
        public int FinancialYearId { get; set; }
        public string VoucherNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> SalaryMonth { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Narration { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AccountLedger AccountLedger { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
        public virtual SuffixPrefix SuffixPrefix { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
