//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsyncAutomateAccountingEntities : DbContext
    {
        public AsyncAutomateAccountingEntities()
            : base("name=AsyncAutomateAccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BarcodeSetting> BarcodeSettings { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<FinancialYear> FinancialYears { get; set; }
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SuffixPrefix> SuffixPrefixes { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<AccountLedger> AccountLedgers { get; set; }
        public virtual DbSet<AdditionalCost> AdditionalCosts { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<PricingLevel> PricingLevels { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<SalaryPackage> SalaryPackages { get; set; }
        public virtual DbSet<AdvancePayment> AdvancePayments { get; set; }
        public virtual DbSet<BankReconciliation> BankReconciliations { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<LedgerPosting> LedgerPostings { get; set; }
        public virtual DbSet<ProductGroup> ProductGroups { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Godown> Godowns { get; set; }
        public virtual DbSet<ModelNumber> ModelNumbers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Rack> Racks { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<BonusDeduction> BonusDeductions { get; set; }
        public virtual DbSet<BudgetDetail> BudgetDetails { get; set; }
        public virtual DbSet<BudgetMaster> BudgetMasters { get; set; }
        public virtual DbSet<CompanyPath> CompanyPaths { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Bom> Boms { get; set; }
        public virtual DbSet<ContraDetail> ContraDetails { get; set; }
        public virtual DbSet<ContraMaster> ContraMasters { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<CreditNoteDetail> CreditNoteDetails { get; set; }
        public virtual DbSet<CreditNoteMaster> CreditNoteMasters { get; set; }
        public virtual DbSet<DailyAttendanceDetail> DailyAttendanceDetails { get; set; }
        public virtual DbSet<DailyAttendanceMaster> DailyAttendanceMasters { get; set; }
        public virtual DbSet<DailySalaryVoucherDetail> DailySalaryVoucherDetails { get; set; }
        public virtual DbSet<DailySalaryVoucherMaster> DailySalaryVoucherMasters { get; set; }
        public virtual DbSet<DebitNoteDetail> DebitNoteDetails { get; set; }
        public virtual DbSet<DebitNoteMaster> DebitNoteMasters { get; set; }
    }
}
