//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendanceDetail
    {
        public int Id { get; set; }
        public int DailyAttendanceMasterId { get; set; }
        public int EmployeeId { get; set; }
        public string Status { get; set; }
        public string Narration { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual DailyAttendanceMaster DailyAttendanceMaster { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
