//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySalaryVoucherDetail
    {
        public int Id { get; set; }
        public int DailySalaryVoucherMasterId { get; set; }
        public int EmployeeId { get; set; }
        public string Wage { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual DailySalaryVoucherMaster DailySalaryVoucherMaster { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
