//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detail()
        {
            this.LedgerPostings = new HashSet<LedgerPosting>();
        }
    
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Columns { get; set; }
        public Nullable<int> Width { get; set; }
        public string DBF { get; set; }
        public string DorH { get; set; }
        public string Repeat { get; set; }
        public string Align { get; set; }
        public string RepeatAll { get; set; }
        public string FooterRepeatAll { get; set; }
        public string TextWrap { get; set; }
        public Nullable<int> WrapLineCount { get; set; }
        public string ExtraFieldName { get; set; }
        public string FieldsForExtra { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Master Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerPosting> LedgerPostings { get; set; }
    }
}
