//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AdvancePayments = new HashSet<AdvancePayment>();
            this.BonusDeductions = new HashSet<BonusDeduction>();
            this.DailyAttendanceDetails = new HashSet<DailyAttendanceDetail>();
            this.DailySalaryVoucherDetails = new HashSet<DailySalaryVoucherDetail>();
        }
    
        public int Id { get; set; }
        public int DesignationId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeCode { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public bool IsActive { get; set; }
        public string Narration { get; set; }
        public string BloodGroup { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string LabourCardNumber { get; set; }
        public Nullable<System.DateTime> LabourCardExpiryDate { get; set; }
        public string SalaryType { get; set; }
        public Nullable<decimal> DailyWage { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BranchCode { get; set; }
        public string PANNumber { get; set; }
        public string PFNumber { get; set; }
        public string ESINumber { get; set; }
        public int DefaultPackageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual SalaryPackage SalaryPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvancePayment> AdvancePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusDeduction> BonusDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyAttendanceDetail> DailyAttendanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailySalaryVoucherDetail> DailySalaryVoucherDetails { get; set; }
    }
}
