//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerPosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LedgerPosting()
        {
            this.BankReconciliations = new HashSet<BankReconciliation>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int VoucherTypeId { get; set; }
        public string VoucherNumber { get; set; }
        public int LedgerId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public int DetailsId { get; set; }
        public int FinancialYearId { get; set; }
        public string InvoiceNumber { get; set; }
        public string Text { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AccountLedger AccountLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankReconciliation> BankReconciliations { get; set; }
        public virtual Detail Detail { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
