//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master()
        {
            this.VoucherTypes = new HashSet<VoucherType>();
            this.Details = new HashSet<Detail>();
        }
    
        public int Id { get; set; }
        public int FormName { get; set; }
        public bool IsTwoLineForHedder { get; set; }
        public bool IsTwoLineForDetails { get; set; }
        public int PageSize { get; set; }
        public int PageSizeOther { get; set; }
        public int BlankLineForFooter { get; set; }
        public string FooterLocation { get; set; }
        public int LineCountBetweenTwo { get; set; }
        public string Pitch { get; set; }
        public string Condensed { get; set; }
        public int LineCountAfterPrint { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherType> VoucherTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Details { get; set; }
    }
}
